title = "De Bacon Tudo"
baseurl = "http://debacontudo.com.br"
languageCode = "pt"
DefaultContentLanguage = "pt"
preserveTaxonomyNames = true
disqusShortname = "debacontudo-com-br"
[taxonomies]
category = "categories"
tag = "tags"
[params]
sidebartitle = "De Bacon Tudo"
sidebartagline = "Porque tudo Ã© bom, especialmente com Bacon"
sidebarphoto = "/img/logo2.png"
gaid = "UA-91331327-1"
[[menu.main]]
name = "Viagens"
url = "/categories/viagem"
[[menu.main]]
name = "Comidas"
url = "/categories/comida"
[[menu.main]]
name = "Estilo de Vida"
url = "/categories/estilo-de-vida"
[[menu.main]]
name = "Pop Culture"
url = "/categories/pop-culture"
[[menu.main]]
name = "Quem Somos"
url = "/quem-somos/quem-somos/"
[[menu.social]]
pre = "<i class='fa fa-twitter'></i>"
url = "http://www.twitter.com/shift8creative"
identifier = "twitter"
[[menu.social]]
pre = "<i class='fa fa-instagram'></i>"
url = "http://www.instagram.com/blogdebacontudo"
identifier = "instagram"
[[menu.social]]
pre = "<i class='fa fa-facebook'></i>"
url = "http://www.facebook.com/debacontudo"
identifier = "facebook"
